### ISSUE TITLE
让你的 Xcode8 继续使用插件 | Vong

### ISSUE THREAD

**Issue by wang9262** [wang9262/Blog-Comments#3]
http://vongloo.me/2016/09/10/Make-Your-Xcode8-Great-Again/

**Comment by panmingyang2009** [comment]
Just for fun!

**Comment by panmingyang2009** [comment]
![](http://ww1.sinaimg.cn/large/ba81ca29gw1evcwqme7gbj20cs0cs74n.jpg)
